global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter:9100']

# Uncomment the following lines to enable scraping from a remote server
# scrape_configs:
#   - job_name: prometheus
#     honor_timestamps: true
#     scrape_interval: 10s
#     metrics_path: /metrics
#     scheme: https
#     static_configs:
#       - targets: ['skippercolt93.duckdns.org:9090']  # Replace with your DNS

#   - job_name: node_exporter
#     scheme: https
#     static_configs:
#       - targets: ['skippercolt93.duckdns.org:9100']  # Replace with your DNS